"""Core module for AutoSOTA."""

from .models import (
    PaperTask,
    ResourceManifest,
    ObjectiveRubricNode,
    IdeaItem,
    RunRecord,
    ErrorSignature,
    SystemState,
    InitReport,
    AgentResponse,
)
from .enums import (
    TaskStatus,
    Phase,
    IdeaType,
    IdeaGranularity,
    IdeaStatus,
    RiskLevel,
    ErrorCategory,
    MonitorAction,
    OptimizationDirection,
)
from .exceptions import (
    AutoSOTAError,
    ResourceError,
    ObjectiveError,
    InitError,
    MonitorError,
    FixError,
    IdeatorError,
    SchedulerError,
    SupervisorError,
    DockerError,
    ParseError,
    StorageError,
    RedLineViolation,
    TimeoutError,
    DependencyError,
)
from .utils import (
    get_logger,
    ensure_dir,
    read_json,
    write_json,
    read_text,
    write_text,
    append_jsonl,
    read_jsonl,
    compute_hash,
    run_command,
    get_git_commit,
    get_git_diff,
    get_file_tree,
    parse_requirements,
    format_timestamp,
    parse_timestamp,
    sanitize_filename,
    truncate_text,
    merge_dicts,
    chunk_list,
    flatten_list,
)

__all__ = [
    # Models
    "PaperTask",
    "ResourceManifest",
    "ObjectiveRubricNode",
    "IdeaItem",
    "RunRecord",
    "ErrorSignature",
    "SystemState",
    "InitReport",
    "AgentResponse",
    # Enums
    "TaskStatus",
    "Phase",
    "IdeaType",
    "IdeaGranularity",
    "IdeaStatus",
    "RiskLevel",
    "ErrorCategory",
    "MonitorAction",
    "OptimizationDirection",
    # Exceptions
    "AutoSOTAError",
    "ResourceError",
    "ObjectiveError",
    "InitError",
    "MonitorError",
    "FixError",
    "IdeatorError",
    "SchedulerError",
    "SupervisorError",
    "DockerError",
    "ParseError",
    "StorageError",
    "RedLineViolation",
    "TimeoutError",
    "DependencyError",
    # Utils
    "get_logger",
    "ensure_dir",
    "read_json",
    "write_json",
    "read_text",
    "write_text",
    "append_jsonl",
    "read_jsonl",
    "compute_hash",
    "run_command",
    "get_git_commit",
    "get_git_diff",
    "get_file_tree",
    "parse_requirements",
    "format_timestamp",
    "parse_timestamp",
    "sanitize_filename",
    "truncate_text",
    "merge_dicts",
    "chunk_list",
    "flatten_list",
]
from .llm_client import LLMClient

__all__.append("LLMClient")
